import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <section className="h-screen bg-gray-800">
          <div className="container h-full py-24">
            <div className="g-7 flex h-full flex-wrap items-center justify-center lg:justify-between">
              <div className="mb-12 md:mb-0 md:w-8/12 lg:w-6/12">
                <img src="../Logo.png" className="mx-auto w-3/4" />
              </div>
              {children}
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
